document:
  title: "SPDX-Builder command line tool"
  organization: "Philips Research"
  comment: "This is an experimental tool"
  key:
  namespace: "https://research.philips.com/spdx-builder"
projects:
  - id: "Gradle:com.philips.research.spdxbuilder:spdx-builder:v0.8.1"
    purl: "pkg:maven/philips/spdx-builder@v0.8.1"
    excluded:
      - "annotation*"
      - "archives"
      - "runtime*"
      - "test*"
curations:
  - purl: "pkg:maven/philips/spdx-builder@v0.8.1"
    license: "MIT"
