document:
  title: "SPDX-Builder command line tool"
  organization: "Philips Research"
  comment:
  key:
  namespace: "https://research.philips.com/spdx-builder"
projects:
  - id: "Gradle:com.philips.research.spdxbuilder:spdx-builder:"
    purl: "pkg:maven/philips/spdx-builder@0.2.0"
    excluded:
      - "annotation*"
      - "archives"
#curations:
#  - purl: "pkg:type/namespace/name@version"
#    source: "https://optional/source/location/uri"
#    license: "<(Optional) License>"
