@startuml

title Black Duck BOM representation

class License {
    UUID
    name:String
    spdxId:String
}

class Origin {
    UUID
    externalNamespace:String
    externalId:String
}
note left of Origin: Provides\nPackage URL

class ComponentVersion {
    UUID + UUID
    name:String
    version:String
    description:String
    ignored:boolean
}
ComponentVersion o--> "*" License: licenses\n<AND/OR>
ComponentVersion o-d-> "*" Origin: origins
ComponentVersion --> "*" ComponentVersion: children

class ProjectVersion{
    UUID
    versionName:String
}
ProjectVersion *-> "*" ComponentVersion: BOM

class Project {
    UUID
    name:String
}
Project *-> "*" ProjectVersion

@enduml
