name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build -x test
    - name: Tests
      run: ./gradlew test
    - name: Show version
      run: ./gradlew -q run --args='--help'
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        comment_title: Unit Test Statistics
        hide_comments: all but latest
        comment_on_pr: true
        files: build/test-results/**/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
