name: Get Licenses 

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  scan:

    runs-on: [self-hosted, research] 

    steps:
    - uses: actions/checkout@v2
    - name: Run ORT scan 
      uses: docker run -v /home/runner/work/spdx-builder/spdx-builder:/project philipssoftware/ort --info analyze -f JSON -i /project -o /project/ort/analyzer
    - name: Create SPDX file
      run: |
        wget https://artifactory-ehv.ta.philips.com/artifactory/dl-innersource-mvn-release/com/philips/research/spdxbuilder/spdx-builder/refs/tags/0.1.1/spdx-builder-refs/tags/0.1.1.jar -O spdx-builder.jar
        java -jar spdx-builder.jar -i ort/analyzer/analyzer-result.json -o spdx-builder.spdx
    - uses: actions/upload-artifact@v2
      with:
        name: licenses 
        path: |
          ort/analyzer/analyzer-result.json 
          spdx-builder.spdx
