name: Get Licenses 

on:
  push:
    branches: 
      - main
      - develop
      - use-tree-format
  pull_request:
    branches:
      - main
      - develop

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.13'
        distribution: 'zulu'
    - name: Download asset
      uses: fabriciobastian/download-release-asset-action@v1.0.6
      with:
        repository: philips-software/spdx-builder 
        file: spdx-builder.jar
        token: ${{ secrets.GITHUB_TOKEN }} 
    - name: Create dependency list
      run: |
        ./gradlew -q dependencies --configuration runtimeClasspath > dependencies.txt
    - name: Create SPDX file
      run: |
        cat dependencies.txt | java -jar spdx-builder.jar tree -f gradle -c .spdx-builder.yml -o spdx-builder.spdx
    - uses: actions/upload-artifact@v3
      with:
        name: licenses 
        path: |
          spdx-builder.spdx
