name: Get Licenses 

on:
  push:
    branches: 
      - master
      - develop
      - add-ort-scan
  pull_request:
    branches:
      - master
      - develop

env:
  SPDX_BUILDER_VERSION: 0.2.1

jobs:
  scan:

    runs-on: [self-hosted, research] 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'
    - name: Run ORT scan 
      run: | 
        docker run -v /home/ec2-user/actions-runner/_work/spdx-builder/spdx-builder:/project philipssoftware/ort --info analyze -f JSON -i /project -o /project/ort
      continue-on-error: true
    - name: Create SPDX file
      run: |
        wget https://artifactory-ehv.ta.philips.com/artifactory/dl-innersource-mvn-release/com/philips/research/spdxbuilder/spdx-builder/refs/tags/${SPDX_BUILDER_VERSION}/spdx-builder-refs/tags/${SPDX_BUILDER_VERSION}.jar -O spdx-builder.jar
        java -jar spdx-builder.jar -i ort/analyzer-result.json -o spdx-builder.spdx
    - uses: actions/upload-artifact@v2
      with:
        name: licenses 
        path: |
          ort/analyzer-result.json 
          spdx-builder.spdx
