name: Scan OSS-review-toolkit

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run ORT scan 
      run: docker run -v $ {{ GITHUB_WORKSPACE }}:/project philipssoftware/ort --info analyze -f JSON -i /project -o /project/ort/analyzer
    - name: Show results
      run: ls project/ort/analyser
